version: '3'
services:
  # app:
  #   build: .
  #   command: python -u ./src/server.py
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./taskcx_app:/usr/src/app/
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
      - 27017:27017
