version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./taskcx:/usr/src/app
    links:
      - db
  worker:
    build:
      context: .
      dockerfile: Dockerfile-jobs
    command: celery --workdir src -A jobs worker --loglevel INFO
    volumes:
      - ./taskcx-job:/usr/src/jobs
    links:
      - db
  db:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"
